Controllers/Test1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using project1.Data.datamodel;
using Microsoft.AspNetCore.Authorization;

namespace adminsite.Controllers
{
  
    public class Test1Controller : Controller
    {
        private readonly DataContext _context;

        public Test1Controller(DataContext context)
        {
            _context = context;
        }

        // GET: N5Vocabs
        public async Task<IActionResult> Index()
        {
            return View(await _context.model1data.OrderByDescending(s => s.OrderId).ToListAsync());
        }

        // GET: N5Vocabs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.model1data
                .Include(m => m.Examples)
                .FirstOrDefaultAsync(m => m.Key == id);
            if (model == null)
            {
                return RedirectToAction(nameof(Index));
            }

            ViewBag.PrevID = id - 1;
            ViewBag.NexID = id + 1;
            return View(model);
        }

        // GET: N5Vocabs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: N5Vocabs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Key,Vocab,Romaji,Hiragana,OrderId,InMyanmar,InEnglish,WordGroup,GroupDetail,Status,CreatedDate,UpdatedDate")] model1 model)
        {
            if (ModelState.IsValid)
            {
                _context.Add(model);
                await _context.SaveChangesAsync();

                int key = model.Key;
                return RedirectToAction(nameof(Details), new { id = key });
            }
            return View(model);
        }

        // GET: N5Vocabs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.model1data.FindAsync(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // POST: N5Vocabs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Key,Vocab,Romaji,Hiragana,OrderId,InMyanmar,InEnglish,WordGroup,GroupDetail,Status,CreatedDate,UpdatedDate")] model1 model)
        {
            if (id != model.Key)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!N5VocabExists(model.Key))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new { id = model.Key });
            }
            return View(model);
        }

        // GET: N5Vocabs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.model1data
                .FirstOrDefaultAsync(m => m.Key == id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // POST: N5Vocabs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var model = await _context.model1data.FindAsync(id);
            _context.model1data.Remove(model);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool N5VocabExists(int id)
        {
            return _context.model1data.Any(e => e.Key == id);
        }
    }
}

Controllers/Test2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using project1.Data.datamodel;
using project1.Extensions;

namespace adminsite.Controllers
{
    public class Test2Controller : Controller
    {
        private readonly DataContext _context;

        public Test2Controller(DataContext context)
        {
            _context = context;
        }

        // GET: N5VocabExamples
        public async Task<IActionResult> Index()
        {
            return View(await _context.model2data.ToListAsync());
        }

        // GET: N5VocabExamples/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.model2data
                .FirstOrDefaultAsync(m => m.ExampleKey == id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // GET: N5VocabExamples/Create
        public IActionResult Create()
        {
            return View();
        }

        // GET: N5VocabExamples/AddOrEdit(Insert)
        // GET: N5VocabExamples/AddOrEdit/5(Update)
        public async Task<IActionResult> AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new model2());
            else
            {
                var model = await _context.model2data.FindAsync(id);
                if (model == null)
                {
                    return NotFound();
                }
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int id, [Bind("ExampleKey,Model1Key,Sentence,InEnglish,InMyanmar,Status,CreatedDate,UpdatedDate")] model2 model)
        {
            if (ModelState.IsValid)
            {
                //Insert
                if (id == 0)
                {
                    model.UpdatedDate = DateTime.Now;
                    _context.Add(model);
                    await _context.SaveChangesAsync();

                }
                //Update
                else
                {
                    try
                    {
                        _context.Update(model);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!N5VocabExampleExists(model.ExampleKey))
                        { return NotFound(); }
                        else
                        { throw; }
                    }
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_View_All", _context.model2data.ToList()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "AddOrEdit", model) });
        }

        // POST: N5VocabExamples/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ExampleKey,Model1Key,Sentence,InEnglish,InMyanmar,Status,CreatedDate,UpdatedDate")] model2 model)
        {
            if (ModelState.IsValid)
            {
                _context.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: N5VocabExamples/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.model2data.FindAsync(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // POST: N5VocabExamples/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ExampleKey,Model1Key,Sentence,InEnglish,InMyanmar,Status,CreatedDate,UpdatedDate")] model2 model)
        {
            if (id != model.ExampleKey)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!N5VocabExampleExists(model.ExampleKey))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        //// GET: N5VocabExamples/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var n5VocabExample = await _context.N5VocabExamples
        //        .FirstOrDefaultAsync(m => m.ExampleKey == id);
        //    if (n5VocabExample == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(n5VocabExample);
        //}

        // // POST: N5VocabExamples/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var model = await _context.model2data.FindAsync(id);
            _context.model2data.Remove(model);
            await _context.SaveChangesAsync();
            return Json(new { html = Helper.RenderRazorViewToString(this, "_View_All", _context.model2data.ToList()) });
        }

        //// POST: N5VocabExamples/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var n5VocabExample = await _context.N5VocabExamples.FindAsync(id);
        //    _context.N5VocabExamples.Remove(n5VocabExample);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool N5VocabExampleExists(int id)
        {
            return _context.model2data.Any(e => e.ExampleKey == id);
        }
    }
}

Views/Test1/Create.cshtml
@model project1.Data.datamodel.model1

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/menu/Layout.cshtml";
}

<h1>Create</h1>

<h4>N5Vocab</h4>
<hr />
<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <label asp-for="Vocab" class="control-label"></label>
                        <input asp-for="Vocab" class="form-control" />
                        <span asp-validation-for="Vocab" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="OrderId" class="control-label"></label>
                        <input asp-for="OrderId" class="form-control" />
                        <span asp-validation-for="OrderId" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Hiragana" class="control-label"></label>
                        <input asp-for="Hiragana" class="form-control" />
                        <span asp-validation-for="Hiragana" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Romaji" class="control-label"></label>
                        <input asp-for="Romaji" class="form-control" />
                        <span asp-validation-for="Romaji" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="WordGroup" class="control-label"></label>
                        <input asp-for="WordGroup" class="form-control" />
                        <span asp-validation-for="WordGroup" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="GroupDetail" class="control-label"></label>
                        <input asp-for="GroupDetail" class="form-control" />
                        <span asp-validation-for="GroupDetail" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="InEnglish" class="control-label"></label>
                        <input asp-for="InEnglish" class="form-control" />
                        <span asp-validation-for="InEnglish" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="InMyanmar" class="control-label"></label>
                        <input asp-for="InMyanmar" class="form-control" />
                        <span asp-validation-for="InMyanmar" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Status" class="control-label"></label>
                        
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group pull-right">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Test1/Delete.cshtml
@model project1.Data.datamodel.model1

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/menu/Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>N5Vocab</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vocab)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vocab)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Romaji)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Romaji)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hiragana)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hiragana)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WordGroup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WordGroup)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupDetail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupDetail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Key" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Test1/Details.cshtml
@model project1.Data.datamodel.model1
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/menu/Layout.cshtml";
}

<a href="~/N5Vocabs/Details/@ViewBag.PrevID">Previous</a>&nbsp;|&nbsp;
<a href="~/N5Vocabs/Details/@ViewBag.NexID">Next</a>
<h1>Details</h1>

<div>
    <h4>N5Vocab</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Vocab)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vocab)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Romaji)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Romaji)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hiragana)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hiragana)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OrderId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.WordGroup)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.WordGroup)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GroupDetail)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GroupDetail)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Key">Edit</a> |
    <a asp-action="Create">Add New</a> |
    <a asp-action="Index">Back to List</a>
</div>
<div id="view-all">
    @await Html.PartialAsync("ViewAll", Model.Examples)
</div>

Views/Test1/Edit.cshtml
@model project1.Data.datamodel.model1

@{
    ViewData["Title"] = "Edit";
  Layout = "~/Views/menu/Layout.cshtml";
}

<h1>Edit</h1>

<h4>N5Vocab</h4>
<hr />
<div class="row">
    <div class="col-offset-2 col-md-8">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Key" />
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <label asp-for="Vocab" class="control-label"></label>
                        <input asp-for="Vocab" class="form-control" />
                        <span asp-validation-for="Vocab" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="OrderId" class="control-label"></label>
                        <input asp-for="OrderId" class="form-control" />
                        <span asp-validation-for="OrderId" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Hiragana" class="control-label"></label>
                        <input asp-for="Hiragana" class="form-control" />
                        <span asp-validation-for="Hiragana" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Romaji" class="control-label"></label>
                        <input asp-for="Romaji" class="form-control" />
                        <span asp-validation-for="Romaji" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="WordGroup" class="control-label"></label>
                        <input asp-for="WordGroup" class="form-control" />
                        <span asp-validation-for="WordGroup" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="GroupDetail" class="control-label"></label>
                        <input asp-for="GroupDetail" class="form-control" />
                        <span asp-validation-for="GroupDetail" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="InEnglish" class="control-label"></label>
                        <input asp-for="InEnglish" class="form-control" />
                        <span asp-validation-for="InEnglish" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="InMyanmar" class="control-label"></label>
                        <input asp-for="InMyanmar" class="form-control" />
                        <span asp-validation-for="InMyanmar" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Status" class="control-label"></label>
                       
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group pull-right">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Test1/Index.cshtml
@model IEnumerable<project1.Data.datamodel.model1>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/menu/Layout.cshtml";
}
<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table" id="tbl">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Vocab)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hiragana)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Romaji)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WordGroup)
            </th>
            <th>
                Meaning
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Vocab)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hiragana)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Romaji)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WordGroup)<br />
                    @Html.DisplayFor(modelItem => item.GroupDetail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InEnglish)<br />
                    @Html.DisplayFor(modelItem => item.InMyanmar)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Key">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Key">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Key">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Test1/ViewAll.cshtml
@model IEnumerable<project1.Data.datamodel.model2>

<h1 class="text-center"><i class="fas fa-comments-dollar text-success"></i> Example List</h1>


<table class="table">
    <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Sentence</th>
            <th scope="col">InMyanmar</th>
            <th scope="col">InEnglish</th>
            <th>
                <a onclick="showInPopup('@Url.Action("AddOrEdit","Test2",null,Context.Request.Scheme)','New Example Sentence')" class="btn btn-success text-white">New Example Sentence</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model)
        {
            <tr>
                <td>@m.ExampleKey</td>
                <td>@m.Sentence</td>
                <td>@m.InMyanmar</td>
                <td>@m.InEnglish</td>
                <td>
                    <div>
                        <a onclick="showInPopup('@Url.Action("AddOrEdit","Test2",new {id=m.ExampleKey},Context.Request.Scheme)','Update Example')" class="btn btn-info text-white"><i class="fas fa-pencil-alt"></i> Edit</a>
                        <form asp-action="Delete" asp-controller="N5VocabExamples" asp-route-id="@m.ExampleKey" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                        </form>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>